title: Erin Shina # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven professional looking for new opportunities. <br><br> 
  Avid reader, musician, and knitter.  <br><br>
  <a href="https://www.linkedin.com/in/erinshina/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
